# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.11
# Mod Properties
mod_version=1.0
maven_group=com.konkitoman
archives_base_name=SSAntiCheat
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.92.2+1.20.1
# Forge
mod_id=ssanticheat
mod_name=SSAntiCheat
mod_authors=[konkitoman]
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.17
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_license=GPL-3.0
mod_description=
dep=org.snakeyaml:snakeyaml-engine:2.7